ipv4_routes:
  - destination: "10.0.0.0"
    subnet_mask: "255.255.255.0"
    next_hop: "192.168.1.1"
  - destination: "10.0.1.0"
    subnet_mask: "255.255.255.0"
    next_hop: "192.168.1.2"
  - destination: "10.0.2.0"
    subnet_mask: "255.255.255.0"
    next_hop: "192.168.1.3"

ipv6_routes:
  - destination: "2001:db8::"
    prefix_length: "32"  # Keeping IPv6 notation
    next_hop: "fe80::1"
  - destination: "2001:db8:1::"
    prefix_length: "48"
    next_hop: "fe80::2"
  - destination: "2001:db8:2::"
    prefix_length: "64"
    next_hop: "fe80::3"

vlans:
  - vlan_id: 10
    name: "Management"
  - vlan_id: 20
    name: ""  # Empty name
  - vlan_id: 30
    name: "Engineering"
  - vlan_id: 40
    # Name field missing

interfaces:
  - name: "GigabitEthernet0/0"
    description: "WAN Interface"
    ip_address: "192.168.100.1"
    subnet_mask: "255.255.255.0"
    ipv6_address: "2001:db8:100::1"
    ipv6_prefix_length: "64"
    status: "up"
    switchport: false
  - name: "GigabitEthernet0/1"
    description: "LAN Interface"
    ip_address: "192.168.200.1"
    subnet_mask: "255.255.255.0"
    ipv6_address: "2001:db8:200::1"
    ipv6_prefix_length: "64"
    status: "up"
    switchport: false
  - name: "GigabitEthernet0/2"
    description: ""  # Empty description
    ip_address: "192.168.300.1"
    subnet_mask: "255.255.255.0"
    status: "down"
    switchport: true  # This is a Layer 2 interface
  - name: "GigabitEthernet0/3"
    status: "up"
    switchport: false

ospf:
  process_id: 1
  router_id: "1.1.1.1"  # Set to None or leave blank to omit
  networks:
    - network: "192.168.100.0"
      wildcard_mask: "0.0.0.255"
      area: "0"
    - network: "192.168.200.0"
      wildcard_mask: "0.0.0.255"
      area: "0"
    - network: "192.168.300.0"
      wildcard_mask: "0.0.0.255"
      area: "1"
  redistribute:
    bgp: true
    rip: false
    static: true
    connected: true

snmp:
  community:
    name: "netman"
    access: "rw"  # Read-write community
  host:
    ip_address: "10.0.60.100"
    version: "2c"

logging:
  trap: "notifications"
  host: "10.0.60.100"
  source_address: "10.0.60.1"