ipv4_routes:
  - destination: "10.0.0.0/24"
    next_hop: "192.168.1.1"
  - destination: "10.0.1.0/24"
    next_hop: "192.168.1.2"
  - destination: "10.0.2.0/24"
    next_hop: "192.168.1.3"

ipv6_routes:
  - destination: "2001:db8::/32"
    next_hop: "fe80::1"
  - destination: "2001:db8:1::/48"
    next_hop: "fe80::2"
  - destination: "2001:db8:2::/64"
    next_hop: "fe80::3"

vlans:
  - vlan_id: 10
    name: "Management"
  - vlan_id: 20
    name: ""  # Empty name
  - vlan_id: 30
    name: "Engineering"
  - vlan_id: 40
    # Name field missing
