name: Pylint Check

on:
  push:
    branches:
      - main 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint  # Install Pylint

      - name: Run Pylint
        run: |
          pylint **/*.py || true  # Lint all Python files in the repository
